### ISSUE TITLE
Error with browserify 4.1.9 and tape-run 0.1.1

### ISSUE THREAD

**Issue by bclinkinbeard** [juliangruber/tape-run#2]
Using the sample code from the readme, to just try this lib out, I get an error. Running

``` js
var test = require('tape');

test('some test', function (t) {
    t.ok(true);
    t.end();
})
```

with `browserify test/*.js | tape-run` produces 

```
Error: spa events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by matiasdecarli** [comment]
Im having this error. @bclinkinbeard could you please tell me more about what was causing your error? (in case you remember, of course)
