### ISSUE TITLE
Error: Not running

### ISSUE THREAD

**Issue by rtsao** [juliangruber/tape-run#23]
I'm using `tape-run` programmatically with electron like so:

```javascript
var browserify = require('browserify');
var run = require('tape-run');

var runner = run();
runner.pipe(process.stdout);

var b = browserify('./test/index.js');
b.bundle().pipe(runner);
```

The tests run properly and the output is fine, but afterwards an error is thrown:

```
net.js:1236
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1236:11)
    at Server.server.destroy (<myproject>/node_modules/server-destroy/index.js:15:12)
    at Electron.<anonymous> (<myproject>/node_modules/browser-run/index.js:97:18)
    at Electron.EventEmitter.emit (events.js:98:17)
    at Electron._exit (<myproject>/node_modules/electron-stream/index.js:96:8)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
```

Wrapping `node_modules/browser-run/index.js:97` in a try/catch fixes the issue. But it seems hacky and I'd rather not use a fork.

It's possible I'm doing something wrong but I'm not sure what.

**Comment by juliangruber** [comment]
that's fixed in browser-run@3.0.5, if you reinstall this module you should get the fixed version of browser-run as well. feel free to reopen if this problem still exists.
