### ISSUE TITLE
Doesn't say much upon errors

### ISSUE THREAD

**Issue by binarykitchen** [juliangruber/tape-run#63]
```
└─( 2 ) ❱❱❱ npm test                                                                                                                                                                                            1 ⏎  +3112 21:31 ❰─┘

> videomail-client@2.0.1 test /home/michael-heuberger/code/videomail-client
> browserify test/**/*.test.js -d -t babelify | tape-run --wait 4000

SyntaxError: Unexpected token :
npm ERR! Test failed.  See above for more details.
```

Using your latest version here. What can I change to get more information on the error? Doesn't tape-run have additional parameters for that? Or can you add a debug mode or so?

**Comment by juliangruber** [comment]
is this code already on github? it's easier for me to debug when i can run it myself

but yeah i agree we should be more helpful here

**Comment by binarykitchen** [comment]
yep, `git clone https://github.com/binarykitchen/videomail-client`, `npm install` and then do a `npm test` @juliangruber

**Comment by juliangruber** [comment]
look at the generated bundle, it starts with non js.

You're right though still that we could be more helpful, this is what node shows:

```bash
 ∴  videomail-client (develop) : ./node_modules/.bin/browserify test/**/*.test.js -d -t [ babelify ] | node
[stdin]:1
babel-preset-env: `DEBUG` option
                ^

SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
    at Socket.<anonymous> (bootstrap_node.js:198:15)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
```

**Comment by juliangruber** [comment]
why babel does that i don't know, but that's not this package's fault

**Comment by binarykitchen** [comment]
ok, i will take this to them from here. for now, can you improve the error handling for this package, so that this stack trace is shown?

**Comment by juliangruber** [comment]
it now shows you where the error is

**Comment by binarykitchen** [comment]
right, thx
