### ISSUE TITLE
option `--chrome` not working

### ISSUE THREAD

**Issue by nichoth** [juliangruber/tape-run#83]
https://github.com/nichoth/wn-blob/blob/main/package.json

It returns 'no matches for chrome' even though chrome is installed

A test:
```
    "test": "browserify -d -p esmify test/index.js | tape-run --browser=\"chrome\" --render=\"tap-spec\""
```

results:
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('no matches for chrome/*')
    at new NodeError (node:internal/errors:371:5)
    at Stream.emit (node:events:383:17)
    at Stream.onerror (node:internal/streams/readable:773:14)
    at Stream.emit (node:events:406:35)
    at Stream.reemit (/Users/nick/code/wn-blob/node_modules/throughout/node_modules/duplexer/index.js:75:16)
    at Stream.emit (node:events:406:35)
    at /Users/nick/code/wn-blob/node_modules/browser-run/index.js:103:29
    at runRunner (/Users/nick/code/wn-blob/node_modules/browser-launcher/index.js:64:14)
    at /Users/nick/code/wn-blob/node_modules/browser-launcher/index.js:74:22
    at /Users/nick/code/wn-blob/node_modules/browser-launcher/index.js:47:22 {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'no matches for chrome/*'
  ```

**Comment by juliangruber** [comment]
I assume that's on mac OS, right?

**Comment by juliangruber** [comment]
I can reproduce this on my mac

**Comment by juliangruber** [comment]
I think the fix is switching to https://github.com/juliangruber/just-launch, as browser-run has been unmaintained from time to time and with the new approach we can easily maintain individual browsers.

**Comment by andrewvmail** [comment]
``` rm -rf ~/.config/browser-launcher/config.json ```
